### ISSUE TITLE
质押赎回时无法全部赎回

### ISSUE THREAD

**Issue by studyzy** [palletone/wallet#29]
点击赎回按钮后，只能输入赎回数量。无法进行全部赎回的操作。
https://github.com/palletone/go-palletone/wiki/Third-Party-Wallet-Contract-Invoke#toc19
API文档中提到：
**如果用户希望提取全部的质押PTN和分红，那么提币金额为：“all”;如果不是全部提取，则是具体的金额（Dao）的数字字符串。**

**Comment by kester001122** [comment]
曾总  关于这问题之前确实考虑过  但是考虑到这实现的UI已经完成，不适合加这个按钮，但是我们做了‘可赎回数量’让用户输入全部数量也是可以的

**Comment by studyzy** [comment]
@kester001122 用户输入数量是无法做到全部赎回这个需求的。比如我现在的质押数量是100，然后我输入赎回数量100，那么系统将会在当天分红后赎回，比如我的分红是1.234，那么我赎回100后，我的账户还是会剩余分红的1.234在里面质押。

**Comment by wzhyuan** [comment]
已增加，全部赎回。会将质押和分红一并赎回。
