### ISSUE TITLE
IOS版本质押操作不能成功

### ISSUE THREAD

**Issue by jialei711** [palletone/wallet#44]
在九月初时候，用安卓注册了咱们的app。因为手机原因，还是找到墙外账号下载了IOS版本。
同一个钱包地址在安卓可以质押但在IOS不能质押，升级版本到2.1后问题依然存在。
钱包地址是：P13BWpFaq1MVnWAVXWFXEybSLG26MEDFpiC

**Comment by wzhyuan** [comment]
已解决
